### ISSUE TITLE
Missing out on ads using the Radlibrary

### ISSUE THREAD

**Issue by JaneD2003** [facebookresearch/Radlibrary#103]
Hi everyone, 
I´m new to R and APIs. I need some data from the Facebook Ad Library. The results from the calls I made do not match with the Facebook Ad Library. I also seem to miss out on some data. What am I doing wrong? 

This is the call I made: queryBW6 <- adlib_build_query(ad_reached_countries = "DE", 
                              ad_active_status = "ALL",
                              ad_type = "POLITICAL_AND_ISSUE_ADS",
                              search_terms = "NULL", 
                              ad_delivery_date_min = "2021-01-31",
                              ad_delivery_date_max = "2021-03-14", 
                              publisher_platforms = c("FACEBOOK", "INSTAGRAM", "MESSENGER", "WHATSAPP"),
                              limit = 1000, 
                              fields = "id")
ads_listBW6 <- adlib_get_paginated(queryBW6, max_gets = 100, token_get())
ads_dfBW6 <- as_tibble(ads_listBW6, type = "ad", censor_access_token = TRUE)
dim(ads_dfBW6)
View(ads_dfBW6) 
I want to take a closer look at Microtargeting from German Parties. The Facebook AdLibrary says, that the page SPD Baden-Württemberg payed for 690 ads in the above named time frame. My API only receives 226 Ads. Some page names do not even appear. Would really appreciate some help, I´m lost.

**Comment by kylescotshank** [comment]
You have the parameter `limit=1000` within your `adlib_build_query()` call. If you remove that, do you get the results that you'd expect?

**Comment by JaneD2003** [comment]
> You have the parameter `limit=1000` within your `adlib_build_query()` call. If you remove that, do you get the results that you'd expect?
unfortunately not. I´m paginating the limit by using adlib_get_paginated(..., max_gets = 100,...) 100*1000. There is space for 100.000 observations and I´m still only getting 27560 observations.

**Comment by madshove-thy** [comment]
@JaneD2003 did you find a solution? I am experiencing a similar problem. For me it's linked to specific pages for a specific period of time (I e.g. have a political party which I have ads for a period of time but not the last 1,5 years where I now and can see in the ad library browser that they have run ads)

**Comment by colin-fraser** [comment]
Hi folks, thanks for raising this and sorry for the response delay! I found the bug and am working on a fix now, and can provide a workaround in the mean time. The problem is that when searching by page_id, the `search_type` parameter is not actually required in the API call, and supplying automatically it is causing some unintended consequences.

@JaneD2003 you're looking for entries for SPD Baden-Württemberg, which [the Ad Library] tool says has "about 690 results" for that time period. 

``` r
library(Radlibrary)
queryBW6 <- adlib_build_query(ad_reached_countries = "DE",
                              ad_active_status = "ALL",
                              ad_type = "POLITICAL_AND_ISSUE_ADS",
                              ad_delivery_date_min = "2021-01-31",
                              ad_delivery_date_max = "2021-03-14",
                              search_page_ids = '179057176050', search_terms = "NULL")

# wrong number of results
adlib_get(queryBW6)
#> Data response object with 263 entries.

# The package won't let us set these to null when we create them, but we can manually set it
# after the fact:
queryBW6$search_terms <- NULL
queryBW6$search_type <- NULL

# right number of results
adlib_get(queryBW6)
#> Data response object with 694 entries.
```

<sup>Created on 2022-09-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

FYI @JaneD2003, the ad library API is not really meant to be used in the way that you're doing it with your first query, for downloading data about all ads in a whole country. It's not that you shouldn't, it's just not the most efficient way to do that. You might have better luck using the [Ad Library Reports](https://www.facebook.com/ads/library/report/) page. The API is better suited for zooming in on a particular subset of ads, like we're doing above.

@madshove-thy you ought to be able to use this same workaround as far as I can tell.

**Comment by colin-fraser** [comment]
@JaneD2003 @madshove-thy this should be fixed in the newest version!

``` r
library(Radlibrary)
queryBW6 <- adlib_build_query(ad_reached_countries = "DE",
                              ad_active_status = "ALL",
                              ad_type = "POLITICAL_AND_ISSUE_ADS",
                              ad_delivery_date_min = "2021-01-31",
                              ad_delivery_date_max = "2021-03-14",
                              search_page_ids = '179057176050')
adlib_get(queryBW6)
#> Data response object with 694 entries.
```

<sup>Created on 2022-09-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Note that you should not include the `search_terms="NULL"` argument.
