### ISSUE TITLE
Page_name?

### ISSUE THREAD

**Issue by michelemeyer** [facebookresearch/Radlibrary#86]
My coding skills are fairly rudimentary, so apologies if this is an obvious question, but what format should page_name arguments take? I am trying to search for all ads posted by different political pages, and I keep getting an "unused argument" error for that field no matter how I format it.

**Comment by colin-fraser** [comment]
Hey Michele! Thanks for using the package!

At the moment there's not a way to search by page name, not because of the Radlibrary but because that's not a search parameter that the ad library API supports. You can see the parameters supported by the API [here](https://developers.facebook.com/docs/marketing-api/reference/ads_archive/v9.0)—to my knowledge, they're all supported in the package.

The API _does_ allow you to search by page ID, and that is supported in Radlibrary. However, it's not totally obvious how to find page IDs. I think you'll have to get these and keep track of them on your own. One way to do that is through the [Ad Library on the web](https://www.facebook.com/ads/library/). If I want to find all Ads related to Joe Biden, I can search for Joe Biden in the Ad Library and click on the link that comes up.
![image](https://user-images.githubusercontent.com/11964090/106398810-cdf69e00-63c9-11eb-9197-09ac68f6afa5.png)
From here, the URL will give away the page ID.
![image](https://user-images.githubusercontent.com/11964090/106398831-f5e60180-63c9-11eb-8fdd-fc423a478412.png)
Pasting this page ID into Radlibrary will let me find all Joe Biden ads.

```
query <- adlib_build_query(ad_reached_countries = "CA", search_page_ids = 7860876103)
```

You can put a vector of up to 10 page IDs into that field.

**Comment by colin-fraser** [comment]
@kylescotshank want to close this? I can't anymore 😭

**Comment by kylescotshank** [comment]
Thanks @colin-fraser! 

Closing.
